#!/usr/bin/env bash

# rofi-ykman
# Yubikey oath utility

#2022 notdodo

OUT="$(mktemp)"

get_code() {
  ykman oath accounts code "$1" > "$2" 2>&1
}

if [ ! "$(ykman info)" ]
then
    dunstify "rofi-ykman" "YubiKey not detected." -a "rofi-ykman"
    exit 1
fi

OPTIONS=$(ykman oath accounts list)
LAUNCHER="rofi -dmenu -i -p YubikeyOATH"

option=`echo "${OPTIONS/, TOTP/\n}" | $LAUNCHER`
if [ ${#option} -le 1 ]; then
  rm $OUT
  exit
fi

get_code "$option" "$OUT" &
sleep 0.5
if grep -q "Touch your" $OUT; then
  dunstify "rofi-ykman" "Touch your YubiKey" -a "rofi-ykman"
  while true; do
    if grep -q "$option" $OUT; then
      sleep 0.5
      break
    fi
  done
else
  ykman oath accounts code "$option" > $OUT
fi 

code=$(cat $OUT | grep "$option")
rm $OUT

IFS=', ' read -r -a code <<< "$code"
if [ $XDG_SESSION_TYPE == "wayland" ]
then
		cliptool=wl-copy
    typer="wtype -"
else
		cliptool="xclip -selection clipboard"
    typer="xargs xdotool type"
fi
if [ "$1" == "type" ]
then
    action=$typer
else
    action=$cliptool
fi
echo "${code[-1]}" | $action
