#!/usr/bin/env bash
# rofi-ykman
# Yubikey oath utility

#2022 notdodo

LAUNCHER="rofi -dmenu -i -p YubikeyOATH"

check_yubikey() {
  if [ ! "$(ykman info)" ]
  then
      dunstify "rofi-ykman" "YubiKey not detected." -a "rofi-ykman"
      exit 1
  fi
}

get_code() {
  ykman oath accounts code "$1" > "$2" 2>&1
}

list_accounts() {
  ykman oath accounts list
}

start_rofi() {
  check_yubikey
  ACCOUNTS=$(list_accounts)
  OPTION=$(echo "${ACCOUNTS/, TOTP/\n}" | ${LAUNCHER})
  if [ ${#OPTION} -le 1 ]; then
    exit
  fi
}

check_code() {
  OPTION=$1
  TEMP_OUT=$2
  while true; do
    sleep 0.2
    if grep -q "Touch your" "${TEMP_OUT}"; then
      dunstify "rofi-ykman" "Touch your YubiKey" -a "rofi-ykman"
      sleep 2
    fi
    if grep -q "${OPTION}" "${TEMP_OUT}"; then
      dunstify "rofi-ykman" "Check your clipboard" -a "rofi-ykman"
      break
    fi
    if grep -q "ERROR" "${TEMP_OUT}"; then
      rm "${TEMP_OUT}"
      break
    fi
  done
}

### MAIN ###
start_rofi
TEMP_OUT="$(mktemp)"
get_code "${OPTION}" "${TEMP_OUT}" &
check_code "${OPTION}" "${TEMP_OUT}"

OTP_CODE=$(grep "${OPTION}" "${TEMP_OUT}")
rm "${TEMP_OUT}"

IFS=', ' read -r -a OTP_CODE <<< "${OTP_CODE}"
if [ "${XDG_SESSION_TYPE}" == "wayland" ]
then
	CLIPTOOL="wl-copy"
else 
  CLIPTOOL="xclip -selection clipboard"
fi
echo "${OTP_CODE[-1]}" | ${CLIPTOOL}
